/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.duanmau.ui;

import com.poly.duanmau.dao.DrinkDAO;
import com.poly.duanmau.dao.impl.DrinkDAOImpl;
import com.poly.duanmau.entities.Drink;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbookprom1
 */
public class DrinkManagementPanel extends javax.swing.JPanel {
    
//  Khai báo đối tượng là interface nhưng khởi tạo đối tượng là class kế thừa
//  Class kế thừa chỉ dùng để ghi đè nội dung các func từ interface định nghĩa
//  Class kế thừa không bổ sung thêm bất kỳ func nào khác 
    private DrinkDAO drinkDAO = new DrinkDAOImpl();
    
//  TH ngược lại nếu lớp kế thừa có bổ sung thêm func 
//  private DrinkDAOImpl drinkDAO = new DrinkDAOImpl();
    
    private List<Drink> drinks;

    /**
     * Creates new form DrinkManagementPanel
     */
    public DrinkManagementPanel() {
        initComponents(); // Khởi tạo các đối tượng control 
        this.getData();
    }
    
//    Load dữ liệu lên table 
//    Dùng cho cho các chức năng CRUD sau khi thực hiện hoàn thành
    private void getData(){
//      Lấy danh sách thức uống từ DB
        this.drinks = this.drinkDAO.getAll();
        DefaultTableModel model = (DefaultTableModel) this.tbDrinks.getModel();
        
//      foreach
        for(Drink drink : drinks){
            model.addRow(new Object[]{
                drink.getId(),
                drink.getName(),
                drink.getUnitPrice(),
                drink.getDiscount(),
                drink.getCategory().getName(),
                drink.isAvailable() ? "Còn hàng" : "Hết hàng"
            });
        }
        
        this.tbDrinks.setModel(model);
    }
    
//  Thêm thức uống vào db
    private void addDrink(){
        // Trước khi thêm và sửa dữ liệu vào db
        // Kiểm tra các dữ liệu ở input 
        Drink drink = this.validateForm();
        if(drink != null){
            this.drinkDAO.create(drink);
            this.getData();
        }
    }
    
    private void updateDrink(){
        // Trước khi thêm và sửa dữ liệu vào db
        // Kiểm tra các dữ liệu ở input 
        Drink drink = this.validateForm();
        if(drink != null){
            this.drinkDAO.update(drink);
            this.getData();
        }
    }
    
//  Thực hiện kiểm tra tất cả nội dung ở input
//  Nếu có bất kỳ lỗi nào ở Input thì return null;
//  Nếu không có lỗi xảy ra thì return đối tượng Drink;
    private Drink validateForm(){
//  Thực hiện kiểm tra
//  - Tên sản phẩm không được bỏ trống
//  - Giá sản phẩm phải là số và phải lớn hơn hoặc bằng 1000
//  - Giảm giá phải là số và nằm trong khoản 0 -> 100
//  - Trạng thái bắt buộc chọn
//  Mỗi lỗi này sẽ thông báo Message tương ứng 
        if(this.tfName.getText().isBlank()){
            // Thông báo popup lỗi
            return null;
        }
        
//    "".isBlank(); => "".trim().isEmpty();
//    "".isEmpty(); => Kiểm tra có ký tự hay không? "  "

        try{
            String price = this.tfPrice.getText();
            int priceInt = Integer.parseInt(price);
            if(priceInt < 1000){
//              Thông báo lỗi 
                return null;
            }
        }catch(Exception e){
//          Thông báo không phải số
            return null;
        }
        
        try{
            String discount = this.tfDiscount.getText();
            double discountDouble = Double.parseDouble(discount);
            if(discountDouble < 0 || discountDouble > 100){
//              Thông báo lỗi 
                return null;
            }
        }catch(Exception e){
//          Thông báo không phải số
            return null;
        }
        
        if(!this.rbtnAvailable.isSelected() && !this.rbtnInavailable.isSelected()){
            return null;
        }
        
        Drink drink = new Drink();
//      Gán giá trị ở các input vào đối tượng drink

        drink.setName(this.tfName.getText());
//      Tương tự với các giá trị còn lại

        return drink;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tfId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDiscount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbtnAvailable = new javax.swing.JRadioButton();
        rbtnInavailable = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cbCategories = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDrinks = new javax.swing.JTable();

        tfId.setEditable(false);

        jLabel1.setText("ID thức uống");

        jLabel2.setText("Tên thức uống");

        jLabel3.setText("Giá");

        jLabel4.setText("Giảm giá");

        jLabel5.setText("Trạng thái");

        buttonGroup1.add(rbtnAvailable);
        rbtnAvailable.setText("Còn hàng");
        rbtnAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAvailableActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnInavailable);
        rbtnInavailable.setText("Hết hàng");

        jLabel6.setText("Danh mục");

        cbCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbDrinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên sản phẩm", "Giá sản phẩm", "Giảm giá", "Trạng thái", "Tên danh mục"
            }
        ));
        jScrollPane1.setViewportView(tbDrinks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtnAvailable)
                                .addGap(26, 26, 26)
                                .addComponent(rbtnInavailable)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDiscount)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbCategories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnAvailable)
                    .addComponent(cbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnInavailable))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAvailableActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCategories;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnAvailable;
    private javax.swing.JRadioButton rbtnInavailable;
    private javax.swing.JTable tbDrinks;
    private javax.swing.JTextField tfDiscount;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
